name: Build Windows binary

on:
  push:
    branches:
      - release

jobs:
  build:
    runs-on: windows-2022
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13.7'

      - name: Cache pip dependencies
        uses: actions/cache@v4
        with:
          path: ~\AppData\Local\pip\Cache
          key: ${{ runner.os }}-pip-3.13.7-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-3.13.7-

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Install offline_folium map files
        run: python -m offline_folium

      - name: Build with Nuitka
        uses: Nuitka/Nuitka-Action@main
        with:
          nuitka-version: main
          script-name: netseedf.py
          mode: standalone
          enable-plugins: pyqt6
          include-package: netCDF4
          include-module: netCDF4.utils
          copyright: 'GNU General Public License v3.0'
          #windows-console-mode: disable
          windows-icon-from-ico: 'icon.png'
          company-name: 'Rok Kuk'
          product-name: 'NetSeeDF'
          file-version: '0.1'

      - name: Upload artifact
        id: artifact_upload
        uses: actions/upload-artifact@v4
        with:
          include-hidden-files: true
          name: dist-build-windows
          path: build



      - name: If executable upload success
        if: steps.artifact_upload.conclusion == 'success'
        run: |
          echo "Executable uploaded successfully" >> $GITHUB_STEP_SUMMARY
          echo "uploaded='true'" >> $GITHUB_OUTPUT

      - name: If executable upload fails
        if: failure() && steps.artifact_upload.conclusion == 'failure'
        run: |
          echo "::warning title=Failed-Upload::\
            Executable couldn't upload. \
            Check available storage at: 'settings > billing > Storage for Actions and Packages'."